backend:
  name: git-gateway

local_backend: true

media_folder: static/images
public_folder: /images

collections:
  - name: "en-finance"
    label: "Finance (EN)"
    folder: "content/en/posts/finance"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Categories", name: "categories", widget: "list", default: ["finance"]}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "en-tech"
    label: "Tech (EN)"
    folder: "content/en/posts/tech"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Categories", name: "categories", widget: "list", default: ["tech"]}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "en-health"
    label: "Health (EN)"
    folder: "content/en/posts/health"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Categories", name: "categories", widget: "list", default: ["health"]}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "en-entertainment"
    label: "Entertainment (EN)"
    folder: "content/en/posts/entertainment"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Categories", name: "categories", widget: "list", default: ["entertainment"]}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "en-politics"
    label: "Politics (EN)"
    folder: "content/en/posts/politics"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Categories", name: "categories", widget: "list", default: ["politics"]}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "en-sports"
    label: "Sports (EN)"
    folder: "content/en/posts/sports"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Categories", name: "categories", widget: "list", default: ["sports"]}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "en-lifestyle"
    label: "Lifestyle (EN)"
    folder: "content/en/posts/lifestyle"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Categories", name: "categories", widget: "list", default: ["lifestyle"]}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
